### ISSUE TITLE
DLL build

### ISSUE THREAD

**Issue by alexlaurence** [layerfMRI/LAYNII#1]
Hi Laynii, apologies if I'm being quite stupid. Could you please include a .dll for this project in the release tab? I'm on a mac and it's a pain to compile...

**Comment by alexlaurence** [comment]
bump.

**Comment by ofgulban** [comment]
Hey are you still having this issue?

**Comment by ofgulban** [comment]
Closing this for now. Can be re-opened if it is needed again.
