### ISSUE TITLE
non-exact rim values 

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#10]
Comment from Roy below:

> ```
> LN_GROW_LAYERS -rim full16_200um_2009b_sym_crop_seg-whole_borders_fix2.nii -vinc 100 -threeD -debug
> ```
> But this gives an empty output file.
> Any idea what I'm doing wrong here?

**Comment by layerfMRI** [comment]
The only time that happen to me what when a drawing program e.g. itk-snap or fslview writes intager values with a scaled float. Then you draw with valuable 2.0. But it ends up beeing 1.99999

Roys case was solved with LN_FLOAT_ME, 
I think it should be included in LN_GROW_LAYERS directly

**Comment by ofgulban** [comment]
This issue should be addressed with the new input data type casting method introduced in v.1.5.0.
