### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by Conxz** [layerfMRI/LAYNII#11]
I am trying to compile the package on a linux machine with `make all` within the laynii folder. But it seems to be not working. That could be a dependency issue? If you have experience related to this, please help. Thanks. 
Here is my env `gcc version 4.8.3 20140627 [gcc-4_8-branch revision 212064] (SUSE Linux)`

> c++ -std=c++11 -DHAVE_ZLIB  -o LN_BOCO src/LN_BOCO.cpp dep/nifti2_io.cpp dep/znzlib.cpp dep/laynii_lib.cpp -I./dep  -lm -lz
dep/laynii_lib.cpp: In function ‘nifti_image* copy_nifti_as_double(nifti_image*)’:
dep/laynii_lib.cpp:352:38: error: call of overloaded ‘isnan(double&)’ is ambiguous
         if (isnan(*(nii_new_data + i))) {
                                      ^
dep/laynii_lib.cpp:352:38: note: candidates are:
In file included from /usr/include/features.h:378:0,
                 from /usr/include/stdio.h:27,
                 from dep/./laynii_lib.h:2,
                 from dep/laynii_lib.cpp:2:
/usr/include/bits/mathcalls.h:234:1: note: int isnan(double)
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from dep/./laynii_lib.h:4:0,
                 from dep/laynii_lib.cpp:2:
/usr/include/c++/4.8/cmath:626:3: note: constexpr bool std::isnan(long double)
   isnan(long double __x)
   ^
/usr/include/c++/4.8/cmath:622:3: note: constexpr bool std::isnan(double)
   isnan(double __x)
   ^
/usr/include/c++/4.8/cmath:618:3: note: constexpr bool std::isnan(float)
   isnan(float __x)
   ^
Makefile:64: recipe for target 'LN_BOCO' failed
make: *** [LN_BOCO] Error 1

**Comment by ofgulban** [comment]
Hi @Conxz ,

Thanks for reporting this issue nicely. It seems that your standard c libraries are not set up therefore the compiler cannot find them.

I am on Debian system therefore I can only guess the required command to install the standard c libraries for your system. But it should be something like this: `sudo zypper install --type pattern devel_basis` which is equivalent to `sudo apt-get install build-essential` in debian as far as I understand.

Let us know if this helps.

**Comment by Conxz** [comment]
Thanks so much @ofgulban !
I tried the compiling on another machine, and it works well. The gcc version is newer on that machine is `gcc version 7.3.1 20180323 [gcc-7-branch revision 258812] (SUSE Linux)`. 
gcc version seems also to matter.

**Comment by ofgulban** [comment]
Thanks for the update @Conxz , glad that it works now. Hopefully this thread will help others having similar issues.
