### ISSUE TITLE
Add LN_RIMIFY program

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#14]
It might be handy to have dedicated program that takes Freesurfer, BrainVoyager etc. (see #13  )segmentation files as input and generates the rim file we often make use of.

- [x] Ability to swap arbitrary integers indicating tissues with LAYNII rim standards.
- [ ] Ability to merge multiple segmentation images (e.g. WM, GM as separate files)
- [x] Ability to borderize (erode + subtraction) inner and outer gray matter voxels.
- [x] Round before typecasting float images into integer to address 1.99999 & 2.00001 -> 2 issue.

**Comment by layerfMRI** [comment]
The below is related
-------------------------------------

Hello Renzo,

Hope you are doing well, I am following your blog and it's been really helpful for me.
I am currently stuck at a problem. I am trying to generate rim file from a binary mask.
I have the whole brain mask for cortical ribbon and white matter with the corresponding MP2RAGE data. But i have been unsuccessful so far can you suggest me something- how to change the weight at the two edges (deep and superficial)

Thank you,
Avinash

-- 
Thanks and Regards,
Avinash Kalyani

PhD (Candidate), Neuroscience
DZNE-IKND
Ex RnD Engineer,
National Brain Research Centre, Manesar, Gurgaon.
M.Tech(Communication and Signal Processing),
IIT Indore.

**Comment by layerfMRI** [comment]
I think the LN_RIMIFY should be able to do to the following: 

- [ ] solve the float precision issue from Roy -> 2.000001 and 1.9999994 should be truncated to 3.
- [ ] permutate values in rim file: 1,2,3 -> 3,2,1, or 1,2,3 -> 2,1,3
- [ ] generate RIM file based on multiple binary masks (GM, WM), or (GM, CSF), or (WM, CSF)

**Comment by layerfMRI** [comment]
In the special request from Avinash:
Until the LN_MIMIFY is released, I would recommend the following AFNI commands instead:

- To generate a binary CSF mask: 3dcalc -a Wholebrain.nii -b WM.nii -expr 'equals(0,a+b)' -prefix CSF.nii -overwrite

- To generate WM border: 3dcalc -a WM.nii -b a+i -c a-i -d a+j -e a-j -f a+k -g a-k -expr 'ispositive(a)*amongst(0,b,c,d,e,f,g)' -prefix WM_border.nii -overwrite

- To generate CSF border: 3dcalc -a CSF.nii -b a+i -c a-i -d a+j -e a-j -f a+k -g a-k -expr 'ispositive(a)*amongst(0,b,c,d,e,f,g)' -prefix CSF_border.nii -overwrite

- Adding them to rim file: 3dcalc -a CSF_border.nii -b WM_border.nii -c Wholebrain.nii -prefix rim.nii -overwrite -expr 'a+2*c+3*b'

**Comment by ofgulban** [comment]
@layerfMRI I will handle this one this week. Then we can iterate on it when/if needed.

**Comment by ofgulban** [comment]
Added the first version of RIMIFY program with f0ccd00155720547d2c0430950a790bc01ad44b7.

**Comment by ofgulban** [comment]
I have also fixed a help message error with 69d1fa1ef056fd6320026076f9d1a3abc869613c which might have caused confusion for some users (above message, and also mentioned by @kwagstyl last week).

**Comment by ofgulban** [comment]
Closing this until a new issue opens as @layerfMRI and I are not needing new features. See `LN2_BORDERIZE` and `LN2_RIMIFY` options.
