### ISSUE TITLE
Readme overhaul

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#16]
As we are iterating rapidly with LAYNII releases, it becomes more apparent that we need to update our readme to have clear instructions for first time users. Current items are:
- [x] Add getting started section for using the executables and source code
- [x] Add links to related tutorials of each program.
- [x] Keep it as short as possible.

**Comment by layerfMRI** [comment]
Links to tutorials are added in v1.5.6 devel.

**Comment by layerfMRI** [comment]
A link to setup instructions is added in the README file: https://layerfmri.com/laynii-setup/

**Comment by layerfMRI** [comment]
Redundancies in the Readme are removed. Especially, I removed the parts that are mentioned in the LAYNII setup blog post now.
The entire list of program compillations is still in there, though. I found it helpful at times.
If we want to make the README file even shorter, we could outsource it to a bash script though (as you, Faruk had it at some point in the past)?

@ofgulban, just see, if this and the above solutions are addressing what you had in mind. If so, jus close the issue.

**Comment by ofgulban** [comment]
I was thinking adding a list of links for the second item. Maybe sth. like this:
### Tutorials
- [LN_LAYER_SMOOTH](https://layerfmri.com/2018/03/15/smoothing-within-layers/)
- [LN_COLUMNS](https://layerfmri.com/2018/09/26/columns/#more-1146)
- so on ...
- 

This is because when I look at the ‘code’ section of layerfMRI blog, there are other entries that are not directly related to LAYNII and also it takes some effort to scroll through to find the wanted tutorial.

**Comment by ofgulban** [comment]
I think such a “quicklinks” list can also be hosted on layerfMRI.com and only linked here in the readme. I am not sure which way is better. @layerfMRI  what do you think?

**Comment by layerfMRI** [comment]
Yes, that's a good idea, its it now included in the Readme file.

**Comment by ofgulban** [comment]
Looks good, and I think this list will be very useful for the new users :)
