### ISSUE TITLE
write LN_HDEDIT

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#17]
Write a new LAYNII program that allows us to manipulate individual fields in a corrupted nii-header.
-> option to copy the geometry of an sampel file (without copying the entire header). This option should not copy the resolution field, the matrix size of the data type field.
-> maybe the option to flip dimensions? 
-> option to get rid of nii_slope and nii_intercept  parameters in header.  Set it to 1 and 0, respectively, while scaling the content of the BRIK. This option should contain a check for quanitzation errors and possible clipping.

**Comment by ofgulban** [comment]
I am unsure about adding this program for 2 reasons:
- Similar things can be done with other major, tried and tested packages (AFNI, FSL), or some scripting (nibabel + python)
- This will increase our maintenance load significantly. I am not sure we need to reinvent the wheel here and prefer focusing on the utilities that does not exist elsewhere.

We need to discuss this further before moving too fast.

**Comment by layerfMRI** [comment]
Fair enough, 
Maybe it's something that can be put in a script and put into the less-maintained [LAYNII_extras](https://github.com/ofgulban/LAYNII_extras) then? 
So far, I failed to use fslcpgeom for it. E.g. because I can't compy the geometry from time series data in short to single TR data in float.

**Comment by ofgulban** [comment]
I think having a few example scripts in LAYNII_extras would do the trick. But maybe there is a special case where other software are not helpful (thought I am doubtful that this is the case).

If the issue continues, maybe send me the problematic data and I will try to do the trick using something you did not try yet (e.g. nibabel).

**Comment by ofgulban** [comment]
Closing for now. We can reopen if/when needed.

**Comment by layerfMRI** [comment]
I uploaded example files now to the shared drive.
[https://drive.google.com/drive/folders/1EHB8aLIhrzc2D2lq26PSn6KCuzDvBolD?usp=sharing](https://drive.google.com/drive/folders/1EHB8aLIhrzc2D2lq26PSn6KCuzDvBolD?usp=sharing)
with an example script using fslcpgeom, which however copies too many fields of the header and turns a 5 MB file into a >100MB file. 
It would be appreciated if you would upload your script to [LAYNII_extras](https://github.com/ofgulban/LAYNII_extras).

**Comment by ofgulban** [comment]
It sounds a bit weird to me that a file size can increase from 5 to 100 mb due to headers. I suspect some typecasting is happening min your case. But I will have a look.

**Comment by layerfMRI** [comment]
Weird right?!? I suspect that the field of dimensions is copied too. (e.g. number of TRs)

**Comment by ofgulban** [comment]
I have checked the files, indeed uint16 datatype voxels were being casted to float32, and this is the reason for the file size increase. However, what you are aiming to achieve is unclear to me. Can you clarify what is the problem further?

**Comment by layerfMRI** [comment]
Sure, It think is fine (and desired) to keep the typecast. It's just unnecessary if FSLCPGEOM has 99 empty time steps, right? 

I would like to have the option to copy the geometry parameters of a header only. I would like to copy it from one file (e.g. native EPI from the scanner) to another (fucntional derivative). I would like to copy nothing else but the location and tilting. No matrix sice, no type-cast, no number of TRs, no resolution etc. 

One of the many applications is that some software packaged screw up the header. Thus, even though there was no spatial transformation whatsoever, the different data do not overline. 
![Screenshot 2020-06-08 at 14 25 36](https://user-images.githubusercontent.com/33968961/84031399-e545ce80-a995-11ea-844e-fdf44b675545.png)

**Comment by ofgulban** [comment]
Have a look at [this python script](https://github.com/ofgulban/LAYNII_extras/blob/master/nifti_swap_affine.py).

I have also added a file to your gdrive folder with `_headerfix` suffix. Have a look and see whether this is what you wanted.

**Comment by ofgulban** [comment]
It seems that we both did not come back to this for almost 2 years. Closing until becomes relevant in the future.
