### ISSUE TITLE
write LN_CHOLMO 

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#18]
Write a new program that takes the already generated layers and padds them with additional layers on either end into WM and CSF. 
E.g. like a negative erosion. 
These padded layers:
-> might not have the same thickness and the GM layers
-> might not be continuous for kissing gyri. 

However, they might be useful for quality control. E.g. to quantify partial volume of false positive activity in WM, or blooming effect of pial vessels outside GM.

**Comment by ofgulban** [comment]
I like this one. This one would play well together with the new `LN2_LAYERS` output.

**Comment by ofgulban** [comment]
What does CHOLMO stands for? :D

**Comment by layerfMRI** [comment]
It follows the tradition to use funny Japanese words as LAYNII programs. 
(following IMAGIRO (inversese ORIGAMI), and LOITUMA ([the leak gir](https://www.youtube.com/watch?v=GCO62VNm67k)l)) its time for the next Japanese invention [CHOLMO](https://www.google.com/search?tbm=isch&q=CHOLMO): 
The ultimate program for padding layers (of cloths)

**Comment by layerfMRI** [comment]
LN2_CHOLMO is no added and can grow layers beyond the '-incl_borders' option in LN2_LAYERS.
I think this issue can be closed.
