### ISSUE TITLE
write LN_IMAGE_SNR

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#19]
While tSNR can be straightforwardly estimated across time with STDEV and MEAN. This is not easy for image SNR, for layer-fMRI time series. 
Common approaches include ->a)  comparing images with and without transmit voltage ->b) phantom signal difference vs. mean (without the presence of physiological noise) ->c) looking at STDEV in brain vs. background. 
None of these approaches are appropriate in layer-fMRI -> GRAPPA invalidates STEV in background -> There is always physiological noise, -> there is not time for extra runs with FA=0.

Glover and Lai 1998 and Feinberg 2013, propose a different mechanism: 
> The even- and odd-numbered time points of a fMRI time series are separately averaged, and the sum and difference of these two images were calculated. The spatial SETEV can be used as a proxy for thermal noise. 

in LN_IMAGE_SNR, now could use a local kernel and use this with Glovers method to obtain a smooth version of an image SNR map.

**Comment by cleanthebrain** [comment]
This feature is now added in 'LN_SKEW'. 
So it will not be necessary to generate an extra program for it 'LN_IMAGE_SNR'.

I think this issue can be closed.
