### ISSUE TITLE
prefix  'dnoised_' added to start of path in LN_MP2RAGE_DNOISE

### ISSUE THREAD

**Issue by Matt-A-Bennett** [layerfMRI/LAYNII#2]
Hi,

I am trying to use your tool `LN_MP2RAGE_DNOISE` in a nipype workflow, and am getting an issue in which the prefix `dnoised_` is added to the beginning of the of the path 
```
ERROR (nifti_image_write_hdr_img2): cannot open output file 'dnoised_/path/to/file/example_subject_anat_uni_image.nii'
```
I have no problem running the tool in bash, python or even as a standalone node in nipype, given that I ensure that I am in the same directory as the data to start with.

So I think my problem in using the tool as part of the nipype workflow has to do with the directory structures that nipype uses.

Is there a way to avoid adding the `dnoised_` prefix to the filename? Or perhaps instead add a suffix e.g. `example_subject_anat_uni_image_dnoised.nii`?

Thanks!

**Comment by ofgulban** [comment]
@Matt-A-Bennett are you still having this problem?

**Comment by ofgulban** [comment]
I have added an optional `-output` flag to `LN_MP2RAGE_DNOISE`. When you use this flag, it will omit the prefix. You can call the output whatever you want. For instance:
```
./LN_MP2RAGE_DNOISE -INV1 sub-001_inv1.nii -INV2 sub-001_inv2.nii -UNI sub-001_uni.nii -output sub-001_uni_denoised
```

To be able to use this, please clone the repository from `devel` branch. I will check with Renzo to get this approval before merging this into `master`. If you still have issues please let us know.

**Comment by ofgulban** [comment]
92cfe233f030f9310f4e74b73e6428b8135a1454 addressed this and it is now merged into `master` branch.

**Comment by Matt-A-Bennett** [comment]
Thanks a lot!
