### ISSUE TITLE
Write LN_ENTROPY

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#20]
Write a new LayNii program that characterizes the local texture of each voxel's surroundings. 

- with option to generate map of local entropy: SDTEV of the value of each voxel with its neighbor (like John Schwarz did to automatically generate rim files). Should be similar to AFNIs 'edge-detect' or Faruk's 'gradient' for 3x3x3 kernels.
- with option to characterize the shape of the entropy for larger kernels. E.g. spherical entropy, or cylindrical entropy, or planar entropy.

**Comment by ofgulban** [comment]
Haha, we had some half-done code for this in segmentator. Maybe time to translate it and complete it in LAYNII :)

**Comment by layerfMRI** [comment]
The [Sobel operator](https://en.wikipedia.org/wiki/Sobel_operator ) and/or its derivatives might be useful here:

**Comment by ofgulban** [comment]
> The [Sobel operator](https://en.wikipedia.org/wiki/Sobel_operator) and/or its derivatives might be useful here:

On a related note: <https://github.com/ofgulban/segmentator/wiki/Deriche-filter> for multi-scale gradients.

**Comment by cleanthebrain** [comment]
The local Entropy aka. the magnitude of the local (3x3x3) gradient strengths is now also added in LN_SKEW for the mean (temporal mean) image. In devel branch.  
I guess this would refer to the Sobel-Feldman operator? I guess it would make sense to make an extra program at some point that is more dedicated for single TR images and also add the Deriche-filter. So I would suggest to keep this issue open.

**Comment by ofgulban** [comment]
I forgot about this issue over time. However, now after re-reading, #65 is connected to the idea here. So I am adding this link between issue.

**Comment by ofgulban** [comment]
Closing this issue until it comes up again for an actual use case
