### ISSUE TITLE
Empty output in LN_LAYER_SMOOTH

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#25]
In version v1.5, the program LN_LAYER_SMOOTH had two bugs"

1. for some cases, the output was empty: 
An example command is:
`LN_LAYER_SMOOTH -layer_file sc_rim_leaky_layers.nii -input sc_rim_layers.nii  -FWHM 10` 
with the data [here](https://drive.google.com/drive/folders/1a1Basby3DzIXHU2DYIatz-9V4d9HDp2S?usp=sharing). 

2. For specific files only, the sulctouch option gives an empty file:
This works fine
`LN2_LAYER_SMOOTH -layer_file layers1.nii -input data1.nii -FWHM 0.1 -mask -sulctouch` 
This gives  an empty file as soon as sulchtouch is on
`LN2_LAYER_SMOOTH -layer_file layers2.nii -input data2.nii -FWHM 0.1 -mask -sulctouch` 
Example data are [here](https://drive.google.com/drive/folders/1rdiSTn0V9-jwKedzYNyIMJFy-k1hvfwK?usp=sharing) 

Because of this bug, the program has been reverted to the version from v1.0 and is currently not in effect for v1.5.6 and later.
Note, the `sulctouch` option has been renamed to `NoKissing` in version 1.5.7.

**Comment by layerfMRI** [comment]
the same program ` LN_LAYER_SMOOTH` had a segmentation fault when a combination of two conditions were fulfilled. 1.) when the mask option was used and 2.) when the input file (to be smoothed) had more than one time point. 
This is fixed now for devel. and for versions later than 1.6.1

**Comment by ofgulban** [comment]
I think we forgot to close this. Closing.

**Comment by chenjl12345** [comment]
Hi there. We have encountered a similar situation. The laynii versions used are 2.0.0 and 2.6.0 under Windows. The data structure is 106 * 86 * 1 * 9000 (only 1 slice and 9000 volumes).
May I ask if this is related to the input time signal or a single slice?
Should we use LN_LAYER-SMOOTH or LN2RAYER-SMOOTH?
LN_2LAYER-SMOOTH seems to be mentioned in issue # 89 as not recommended for use.
Any help would be greatly appreciated, thank you!

**Comment by ofgulban** [comment]
Hi @chenjl12345 , thanks for opening this issue. 

Would it be possible for you to send us your data (e.g. a smaller version would be enough 106 * 86 * 1 * 10)? So that we can inspect your input and replicate the empty output.

**Comment by chenjl12345** [comment]
> Hi [@chenjl12345](https://github.com/chenjl12345) , thanks for opening this issue.
> 
> Would it be possible for you to send us your data (e.g. a smaller version would be enough 106 * 86 * 1 * 10)? So that we can inspect your input and replicate the empty output.

Thank you for your help, and I apologize for wasting time. I think our problem comes from the incorrect use of `-NoKissing` in the cerebral cortex of rodent that do not need to consider gyri.

**Comment by ofgulban** [comment]
Ah ok, glad to hear that you figured it out :)
