### ISSUE TITLE
LN BOCO issue when input nifti header scl_slope=0

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#26]
After the slope fix, the output is all zero. 
LN_BOCO is now reverted to v1.5.6. 

Comand:  LN_BOCO -Nulled Nulled_intemp.nii -BOLD BOLD_intemp.nii -output VASO_LN.nii
example data: https://drive.google.com/drive/folders/1F63Y9b_w9TBOUGWwH-cyAF6haLV9piSP?usp=sharing

**Comment by ofgulban** [comment]
This was due to the input images having `scl_slope = 0.0000`. So the program was actually working correctly :D

I will put a special case handling for this. But you might want to check how you create these niftis. Some of their headers look strange.

**Comment by layerfMRI** [comment]
Awesome thanks for the super fast fix. 
could you apply the  same fix in LN_MP2RAGE_DENOISE?
It got problems there too.

**Comment by ofgulban** [comment]
Sure, it is coming right up! :)
