### ISSUE TITLE
Error when compiling LN2_LAYERS

### ISSUE THREAD

**Issue by gjheij** [layerfMRI/LAYNII#27]
Hi,

I'm trying to re-install laynii but I get the following error when compiling LN2_LAYERS:

`src/LN2_LAYERS.cpp:1094:43: note: candidates are:
In file included from src/../dep/laynii_lib.h:5:0,
                 from src/LN2_LAYERS.cpp:13:
/usr/include/stdlib.h:770:12: note: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;`

Any suggestions?

Best,
Jurjen Heij
Spinoza Centre for Neuroimaging

**Comment by layerfMRI** [comment]
Hi Jurjen,
Strange, it looks like a stdlib weirdness. People have told me to get rid of it. 
I think I could fix it by replacing it with m*m. 
could you try again with the latest version?

**Comment by gjheij** [comment]
Works like a charm, thanks!
