### ISSUE TITLE
Volume cropping with LN_GRADSMOOTH proportional to smoothing fwhm

### ISSUE THREAD

**Issue by vipfa100** [layerfMRI/LAYNII#29]
Hi everyone,

I am using the precompiled LAYNII v 1.5.6 on an Ubuntu 16.04 subsystem on Windows 10. When I use LN_GRADSMOOTH, I noticed that my image is being cropped depending on how big I select my smoothing fwhm (see attached figure ). The images are angulated with a lot of zeros in it so maybe the issue relates to that. I see this behavior with and without adding a mask. 

the command I use:

```
LN_GRADSMOOTH  -gradfile meanrs1_echo4.nii -input rs1_echo1_00001.nii -output smrs1_echo1_00001.nii -mask func_mask_weighted.nii -FWHM 1 -within -selectivity 0.1
```       

![cropping](https://user-images.githubusercontent.com/73169480/96587028-15a55e00-12e2-11eb-86b8-4f9cc84b998e.png)

**Comment by layerfMRI** [comment]
Thanks Viktor, 
would you mind sharing an example image so we can make sure if our hypothesized solution really help. A single TR and would be enough I think. 
Best regards, 
Renzo

**Comment by vipfa100** [comment]
Sure I am currently uploading the images I mentioned and I will provide you with a download link in a second

**Comment by ofgulban** [comment]
@renzohuber during the usage of the gaussian kernel, we need to prevent masked voxels going into the sum and the divisor.

@vipfa100 thanks for reporting this issue.

**Comment by layerfMRI** [comment]
I think the masking is supposed to happen already during the Kernel generation. That's why there all the if loops in there ;-) 
maybe it happens with the application of the kernel? The test data will make it clearer

**Comment by vipfa100** [comment]
Hey guys,

I just checked LN_GRADSMOOTH with non-angulated images and there the masking and smoothing works correctly. I used a 3 mm kernel and and the edges of the image are nicely preserved. Maybe this helps you to track down the source :)

**Comment by ofgulban** [comment]
Thanks @vipfa100 , looking at the code and your data, I see what needs to be done. This program needed a few “under the hood” improvements anyway in addition to fixing this behavior.

**Comment by layerfMRI** [comment]
I believe the problem comes from the fact that voxel values outside the slab are NANs (not a number, e.g. look at it in FSLeyes). And, the smoothing with NAN values are now defined.
As far as I can see, there are two easy fixes.

1. I replaced the NANs with zeroes before I ran it through LN_GRADSMOOTH and it worked fine. 
example data: https://drive.google.com/file/d/1iE764Vx2fYbVEmdE4Nled0B4PCa_nLxg/view?usp=sharing 

2.) The program LN_GRADSMOOTH still uses previous versions of the nii-I/O. In the most current version, Faruk checks for NANs before loading the dataset. This could be fixed at our end without too much trouble. I guess this is what Faruk refers to as "under the hood improvements.

**Comment by vipfa100** [comment]
Ah that is excellent. Then for now I will get rid of the NANs before I pass the input the LN_GRADSMOOTH until you are ready for a new version push :) 

Thanks guys 👍

**Comment by ofgulban** [comment]
@vipfa100 `NaN`s in input files should be overwritten by `0`s now upon loading the niftis, with commit 12b3d337832bf2ba2f4e93e579f8777db298586f . If you wish you can try compiling from our devel branch and see if it has any effect.

**Comment by vipfa100** [comment]
Hey Faruk,

thanks man that was very quick! Yes I'll try to compile it. If I may be bold to suggest a new feature: it would be cool if the the mask only has an effect on the determination of the smoothing kernel but is not actually applied to the final image. 

For instance one could use a mask which explicitly excludes large veins determind by a e.g. SWI image. But this veins should not be masked out in the final image, just not contribute to the smoothing operation. With that you could see the intravascular effect in those vessels while having nice smooth non-vascular tissue.

Just a suggestion. Perhaps it might be usefull to some people. If they want, they could still apply the mask posthoc after smoothing.

**Comment by ofgulban** [comment]
New feature for `LN_GRADSMOOTH`, `-keep_masked` flag added with 88168a8c11206c35df72cdd2f314db235ffe0593 . It seems to work for me but feel free to try and let us know @vipfa100 .

**Comment by vipfa100** [comment]
Hey guys,

just wanted to inform you.  `-keep_masked` works :)

Thanks again.

**Comment by ofgulban** [comment]
Thanks for the feedback, closing this issue :)
