### ISSUE TITLE
Add literature reference to README

### ISSUE THREAD

**Issue by TimVanMourik** [layerfMRI/LAYNII#3]
It would be really nice to add to the README a mention what paper needs to be cited if LAYNII is used 🙂

**Comment by ofgulban** [comment]
@TimVanMourik , thanks for bringing this up. There is no software paper yet, I saw people using the following reference for now (@layerfMRI correct me if I am mistaken):
- Huber, L., Tse, D. H. Y., Wiggins, C. J., Uludağ, K., Kashyap, S., Jangraw, D. C., Bandettini, P. A., Poser, B. A., & Ivanov, D. (2018). Ultra-high resolution blood volume fMRI and BOLD fMRI in humans at 9.4 T: Capabilities and challenges. NeuroImage. https://doi.org/10.1016/j.neuroimage.2018.06.025

The used version of LAYNII can be cited using the Zenodo link (though I think, we might need to tidy that up a bit @layerfMRI ):
https://doi.org/10.5281/zenodo.3514297

**Comment by ofgulban** [comment]
Addressed with cacf17281a8e099f4a844385e3c176ec0283452c.
