### ISSUE TITLE
Revise LN_GRADSMOOTH and LN_GRADSMOOTH_ITER

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#30]
There was a point a few months back where we had to regress `LN_GRADSMOOTH` code to prevent a segmentation fault.

Together with Issue #29 , and regardless of it being solved or not in the short term, I need to review & revise `LN_GRADSMOOTH` & `LN_GRADSMOOTH_ITER` to make their code coherent with the rest of LAYNII. 

- [x] `LN_GRADSMOOTH` 
- [x] `LN_GRADSMOOTH_ITER`

**Comment by ofgulban** [comment]
I have revised `LN_GRADSMOOTH_ITER`, but I am not sure why this program is needed compared to `LN_GRADSMOOTH`. I saw some Kabir related lines, do need to keep this program in the long run?

**Comment by layerfMRI** [comment]
Thanks for revising. 
We had invested a few weeks on it last summer and ultimately decided that it did not end up working for our purposes in practice. While it is faster than `LN_GRADSMOOTH` and while it minimizes signal leakage across kissing gyri, the underlying mechanism and its selectivity is not comparable with the one used in `LN_GRADSMOOTH`. I would be fine with removing `LN_GRADSMOOTH_ITER' (while keeping it somewhere in the archive for potential later use). I would not waste time to merge is with `LN_GRADSMOOTH`. Too low in the priority list.

**Comment by ofgulban** [comment]
Thanks. I have archived `LN_GRADSMOOTH_ITER` together with a few other experimental programs with 73a3b3608aad7740323fc5500578bd34ea2008ae .
