### ISSUE TITLE
LN2_COLUMNS disconnected mid-GM bug

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#34]
LN2_COLUMNS does not generate columns exhaustively when there are multiple disconnected clusters of mid-GM.

**Comment by ppxdm4** [comment]
Hi @ofgulban thank you for meeting with us on Monday. Just to update you, I have managed to run the new connected-cluster version of LN2_COLUMNS on our entire GM mask with no issues.

**Comment by ofgulban** [comment]
@ppxdm4 , excellent news :). Do let us know if you encounter other issues.
