### ISSUE TITLE
LN2_PATCH_FLATTEN for functional time series data. 

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#38]
I believe that `LN2_PATCH_FLATTEN` might also be useful to brows functional MRI data through time in this flattened fashion. 
E.g. to follow the vessels' response across time (inspiration of unfolded cortex: https://youtu.be/y8FaZHwf4dM?t=1261)
Thus, at some point it might make sense to also allow time series data as input to `-value` argument.

**Comment by ofgulban** [comment]
Absolutely agree. I can add this functionality straightforwardly.

**Comment by ofgulban** [comment]
This functionality is added now as mentioned in #59 .
