### ISSUE TITLE
LN_BOCO -shift option has problem with scl_slope = 0

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#39]
The _correl.nii output file is all filled with values of nan or 0.

**Comment by zqsha** [comment]
Hi Renzo,
I am using the up-to-date version of Laynii, however, this issue remains. Specifically, I used the following command line to run motion correction.

# separating images
echo "seperating $n_vols time steps to save RAM"
ImageMath 4 vol_.nii TimeSeriesDisassemble nulled.nii

# removing steady state effects 
rm -f vol_1000.nii vol_1001.nii
cp -f vol_1002.nii vol_1000.nii 
cp -f vol_1003.nii vol_1001.nii

# motion correction
for i in $(eval echo "{$basevol..$nthvol}");
do
antsRegistration \
--dimensionality 3 \
--float 1 \
--collapse-output-transforms 1 \
--output [ vol_${i}_,vol_${i}_Warped.nii.gz,1] \
--interpolation BSpline[2] \
--use-histogram-matching 1 \
--winsorize-image-intensities [ 0.005,0.995 ] \
-x moma.nii \
--initial-moving-transform [ n_reference.nii,vol_${i}.nii,1 ] \
--transform Rigid[ 0.1 ] \
--metric MI[ n_reference.nii,vol_${i}.nii,1,32,Regular,0.25 ] \
--convergence [ 250x100,1e-6,10 ] \
--shrink-factors 2x1 \
--smoothing-sigmas 1x0vox \
--transform SyN[ 0.1,3,0 ] \
--metric CC[ n_reference.nii,vol_${i}.nii,1,2 ] \
--convergence [ 50x0,1e-6,10 ] \
--shrink-factors 2x1 \
--smoothing-sigmas 1x0vox
done

echo "reassembling the time points"
tr=1
ImageMath 4 moco_nulled.nii TimeSeriesAssemble $tr 0 vol_*_Warped.nii.gz

And then I used the same pipeline to correct head motion for non-nulled images. Afterward, the output images look very good.

# temporal upsampling so VASO matches BOLD
echo "temporal upsampling and shifting happens now"
3dUpsample -overwrite -datum short -prefix Nulled_intemp.nii -n 2 -input moco_nulled.nii
3dUpsample -overwrite -datum short -prefix BOLD_intemp.nii -n 2 -input moco_nonnulled.nii

NumVol=`3dinfo -nv Nulled_intemp.nii`
3dTcat -overwrite -prefix Nulled_intemp.nii Nulled_intemp.nii'[0]' Nulled_intemp.nii'[0..'`expr $NumVol - 2`']'

echo "BOLD correction happens now"
/project/bbl-bgd/software/LayNii_v2.4.0/LN_BOCO -Nulled Nulled_intemp.nii -BOLD BOLD_intemp.nii

However, the output VASO_LN.nii is filled with nan, as follows,
![image](https://github.com/layerfMRI/LAYNII/assets/27337033/3d0c332b-c85d-423b-9638-bc5070a7273b)

Do you have any thoughts about this issue?

Thanks,
Cain

**Comment by zqsha** [comment]
Hi experts,
Thanks for clearing it up. These details are very helpful for me to understand the function of LN_BOCO and how it works. Problem solved! After I removed some noise images from the nii files, it works very well. Thanks again for your comments. I will take notes of it. :-)
