### ISSUE TITLE
How to compute local cortex orientation in LayNii?

### ISSUE THREAD

**Issue by jiaen-liu** [layerfMRI/LAYNII#41]
Hi 

I'm wondering if laynii calculates the normal direction of the cortex. If so, how is it done?
Thanks

Jiaen

**Comment by ofgulban** [comment]
Hi @jiaen-liu ,

Thanks for posting this question.

Practical answer is, use LN2_LAYERS with `-streamlines` flag:
```
    -streamlines  : (Optional) Export streamline vectors. Useful for e.g.
                    computing B0 angular differences. Off by default.
```
This will generate an additional 4D nifti file, where the 4th dimension has 3 volumes encoding voxel-wise local orientation vectors. You can visualize this 4D nifti file in FSLEYES as `3 direction vector image` (see below):
![Screenshot_2021-07-02_12-59-47](https://user-images.githubusercontent.com/4668327/124264983-72c20680-db35-11eb-8ae3-9212022f9167.png)

How the "local cortex orientations" (or as we call "streamlines") are computed is indirectly explained in Figure 3 at <https://thingsonthings.org/ln2_layers/>. Basically, for each voxel, we find the closest inner gray matter border and closest outer gray matter border (geodesically). And compute these streamlines after averaging these two vectors and normalizing them to unit length.

**Comment by jiaen-liu** [comment]
Terrific. That's a very useful function!

**Comment by ofgulban** [comment]
Thanks!!! Actually this was an accidental discovery while building the LN2_LAYERS :))

However, do bear in mind that I did not tested the `-streamlines` output on varying types of niftis yet. There might be some cases where the vector orientations might be buggy (when non-standard nifti headers are used). If you recognize the vectors pointing at wrong directions, let us know. 

In addition, I was using these streamlines to compute the local angular differences with regards to B0. An example python script that does this can be found at: <https://github.com/ofgulban/LAYNII_extras/blob/master/demo-B0_angular_difference/04_B0_angles.py> . We might incorporate this at some point to LN2_LAYERS for convenience in the future.
