### ISSUE TITLE
Output_example_analysis

### ISSUE THREAD

**Issue by Frasera1975** [layerfMRI/LAYNII#42]
HI all

This seems like a minor issue but I am not getting an output I expected from one of the scripts on the online example script (https://layerfmri.com/2019/03/22/analysispipeline/) and its preventing me completing the analysis. Specifically from the LAYNII BOCO (bold correction script). Where the script says 
```
echo "temporal upsampling and shifting happens now"
3dcalc -a Nulled_Basis_b.nii'[1..$(2)]' -expr 'a' -prefix Nulled.nii -overwrite
3dcalc -a Not_Nulled_Basis_a.nii'[0..$(2)]' -expr 'a' -prefix BOLD.nii -overwrite
3dUpsample -overwrite  -datum short -prefix Nulled_intemp.nii -n 2 -input Nulled.nii
3dUpsample -overwrite  -datum short -prefix BOLD_intemp.nii   -n 2 -input   BOLD.nii
NumVol=`3dinfo -nv BOLD_intemp.nii`
3dTcat -overwrite -prefix Nulled_intemp.nii Nulled_intemp.nii'[0]' Nulled_intemp.nii'[0..'`expr $NumVol - 2`']' 

echo "BOLD correction happens now"
LN_BOCO -Nulled Nulled_intemp.nii -BOLD BOLD_intemp.nii -trialBOCO 40

echo "I am correcting for the proper TR in the header"
3drefit -TR 1.5 BOLD_intemp.nii
3drefit -TR 1.5 VASO_LN.nii
```

I don't know where the `VASO_LN.nii` is created and I dont seem to have it in my directory after running the BOCO script but I do have the BOLD_intemp and the nulled_intemp.nii and it gives me a error and then later a fatal error(see below)

```
OLD_intemp.nii  mean_nulled.nii     Nulled_intemp.nii
BOLD.Mean.nii    mocobatch.m         Nulled.nii
fra20@bioeng342-pc:~/Example_data/EPI_analysis$ ./BOCO,sh
bash: ./BOCO,sh: No such file or directory
fra20@bioeng342-pc:~/Example_data/EPI_analysis$ ./BOCO.sh
The script starts now:  I expect two files Not_Nulled_Basis_a.nii and Nulled_Basis_b.nii that are motion corrected with SPM
temporal upsampling and shifting happens now
++ 3dcalc: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./Nulled.nii
++ 3dcalc: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./BOLD.nii
++ 3dUpsample: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ Authored by: RWCox
++ 3dUpsample: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ Authored by: RWCox
++ 3dTcat: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ elapsed time = 0.3 s
BOLD correction happens now
./BOCO.sh: line 16: LN_BOCO: command not found
I am correcting for the proper TR in the header
++ 3drefit: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset BOLD_intemp.nii
 + changing TR
 + loading and re-writing dataset BOLD_intemp.nii (/home/fra20/Example_data/EPI_analysis/BOLD_intemp.nii in NIFTI storage)
++ 3drefit processed 1 datasets
++ 3drefit: AFNI version=AFNI_21.2.01 (Jul 14 2021) [64-bit]
++ Authored by: RW Cox
** ERROR: Can't open dataset VASO_LN.nii
++ 3drefit processed 0 datasets
calculating T1 in EPI space
```

This makes me uncertain of the rest of the analysis. Has anyone had this issue before or am i missing something

Best wishes
Fraser

**Comment by layerfMRI** [comment]
Hi Fraser, 

Thanks for opening this 'issue'
While this pipeline example is from the LayNii aera from before version 1.6, it should still be executable right now. 

It looks to me that the LayNii program LN_BOCO is not found. Thus, its output VASO_LN.nii is never created in the first place. 
Common reasons for this is that:

1. LayNii is not installed or not compiles yet. 
2. There are no paths set to the binaries of LayNii. E.g. executing is as LN_BOCO not /PATH_TO_BINARIES/LN_BOCO.

Best regards, 
Renzo

**Comment by Frasera1975** [comment]
Hi Renzo

Thanks for that. I will look again at the install

Best wishes
Fraser

**Comment by ofgulban** [comment]
@Frasera1975 , one easy thing to try can be:
1. Download & unzip the compiled LayNii programs (zip files from <https://github.com/layerfMRI/LAYNII/releases> expanding the  *assets* sections)
2. give full path to `LN_BOCO` by writing `/path/to/unzipped_laynii_folder/LN_BOCO -Nulled Nulled_intemp.nii -BOLD BOLD_intemp.nii -trialBOCO 40` instead of `LN_BOCO -Nulled Nulled_intemp.nii -BOLD BOLD_intemp.nii -trialBOCO 40` in your script.

**Comment by Frasera1975** [comment]
Hi Omer

Thats very helpful. Much appreciated. Will try the full path as suggested 

Best wishes
Fraser

**Comment by Frasera1975** [comment]
HI Omer and Renzo

Thank you. Your advice worked. I added the full path to the script and all
was well. Silly error on my part as I thought I had added LayNii to the
permanent path

best wishes
Fraser

**Comment by ofgulban** [comment]
Hi @Frasera1975 ,

Happy to hear that it worked :) good luck with your analyses and feel free to continue posting your issues here. Surely such threads will help others having similar issues in the future.
