### ISSUE TITLE
GRE field map for laminar fMRI

### ISSUE THREAD

**Issue by giobattistella** [layerfMRI/LAYNII#43]
Hi,

My laminar fMRI protocol is composed of 75 sagittal slices acquired with an isotropic voxel-size of 0.8 mm. I was wondering if I should add a gre-field map acquisition or spin-echo with opposite phase encoding to use for distortion correct of fMRI data.

Thank you very much for your help.
Cheers,
Giovanni

**Comment by ofgulban** [comment]
Hi @giobattistella ,

This question is a bit out of topic for our software package. Having said this, I would still be cautious for giving any advice to you as I do not know many other parameters in your experiment and acquisition.

However, I might suggest an excellent review paper which might help:
- Polimeni, J. R., Renvall, V., Zaretskaya, N., & Fischl, B. (2018). Analysis strategies for high-resolution UHF-fMRI data. NeuroImage, 168(April), 296–320. <https://doi.org/10.1016/j.neuroimage.2017.04.053> [Section **Distortion-matched functional and anatomical data**]

**Comment by giobattistella** [comment]
Thank you very much, @ofgulban. I will go over this exciting paper in detail to get more information.

Cheers,
Giovanni
