### ISSUE TITLE
Activation Image resolution Delta bold/vaso exmaple data set

### ISSUE THREAD

**Issue by Frasera1975** [layerfMRI/LAYNII#44]
HI all

I have worked through the online tutorial to the activation stage of the example data. Everything seems to have run fine. Both the delta bold and delta VASO images appear identical to the data sets in the video. However, when I go to look at the activation at the suggested values I do seem to get the same activation patterns but I do not have the same image resolution of the brain in the background as in the clip. In fact, I totally lose the brain image altogether. I wondered why this might be as it makes assessing the location of the activation impossible. I wondered if anyone had come across this issue previously? Just to confirm I am using FSLeyes.

**Comment by Frasera1975** [comment]
Solved this

**Comment by Frasera1975** [comment]
@layerfMRI Many thanks for your reply and apologies for the delayed response (on leave). Ah, thank you, that makes sense now. I will look at using ANTS in future.  I got around the issue via a basic (but sub-optimal) way by simply playing with the FSLeyes viewing and activation parameters so that I could just make out my ROI in conjunction with an educated estimate. After a couple of attempts, the analysis seemed to make sense so was ok for now at least.

**Comment by ofgulban** [comment]
Seems resolved. Closing.
