### ISSUE TITLE
LN_ZOOM error

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#5]
`LN_ZOOM.cpp` compiles but gives an error when writing output at the end of execution. @layerfMRI can you have a look at it? 
*Note:* Try solving the issue when you are at `devel` branch first, if the new structure feels strange you can try solving it in `master` (which has the familiar structure).

**Comment by layerfMRI** [comment]
thanks for the issue, @ofgulban.
I think it might have been due to a data type issue. I included a few more of the common data types and tested it. So it seems to work for me. 
If it still doesn't work for you, please let me know and send me a link to your file.

**Comment by ofgulban** [comment]
@layerfMRI thanks for looking into this. After your fix I have detected another bug and fixed it with 9f7c1627ef514ae02aa3e85469b3b27307fd8ec5 . This bug was preventing the max x, y, z slices to appear in the output.
