### ISSUE TITLE
Maximum datasize in LayNii is not clear. 

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#54]
I tried to use LN_BOCO on a relatively large time series. The output was all zeroes. 

I tried it on other programs (LN_INFO and LN_SKEW) with the result of a 'segmentation fault'.
The number of Voxels is 240 x 240 x 120 for 460 repetitions (3,179,520,000 voxels). 
This is less than the limit of Nifit of 2^32 = 4,294,967,296. 

Everything works fine if I execute it on the first 10 TRs only. 
I should figure out what the hard limits are in the Nii-IO that we are using and put it in the documentation. 

So far, I could rule out other issues. E.g. corrupted nii header due to scl_slope. 
Link to data: https://drive.google.com/drive/folders/1MNkMvrJE3JbheDBqq0-8DvQ-LMYpsMgW?usp=sharing

**Comment by layerfMRI** [comment]
Update: 
Empirically, it seems to break down at 2^31 voxels = 2,147,483,648
Namely: it runs without problems for 2,142,720,000 voxels, but it breaks with 2,149,632,000 voxels.
I think this is something that I can live with. And I think it does not need fixing.
But it should be mentioned somewhere in the documentation, I guess.

**Comment by ofgulban** [comment]
Closing this issue until a new related issue rises.
