### ISSUE TITLE
LN2_LAYERS - empty equivol files

### ISSUE THREAD

**Issue by ravenep** [layerfMRI/LAYNII#55]
Hello!

I have a small issue on basic usage I was hoping to get your help on. I start here to generate 3d whole brain rimified data. The data are macaque, and have been upsampled to 0.25 isotropic voxel size. 

LN2_RIMIFY -input pve_classify.nii -innergm 3 -outergm 1 -gm 2 -output rim.nii

<img width="1353" alt="Screen Shot 2022-06-15 at 11 41 17 AM" src="https://user-images.githubusercontent.com/12449573/173869081-44f0e0cb-5b1e-4544-b11c-f43f80a31222.png">

I then try LN2_LAYERS. It generates the midGM, but does not seem to make the layers themselves. The files are made but empty. Do you have some idea of what I might be doing wrong here?

LN2_LAYERS -rim rim.nii -nr_layers 20 -equivol -iter_smooth 100

<img width="1347" alt="Screen Shot 2022-06-15 at 11 39 27 AM" src="https://user-images.githubusercontent.com/12449573/173869097-f6f8c617-f93f-4429-8f81-d150dcd779bd.png">

Thanks for any insight!

**Comment by ofgulban** [comment]
Hi @ravenep ,

that seems strange, can you post the full list of the outputs generated by LN2_LAYERS, maybe together with the terminal output?

**Comment by ofgulban** [comment]
Can you check if the min max range of fsleyes is adjusted properly? May they just look empty because min max are the same number in fsleyes. I saw this behavior before

**Comment by ravenep** [comment]
Thanks for your message. I did check in a few different viewers with different scalings (mrtrix, fsleyes, wbview) but no luck. Happy to share a data set if that is easier. I also tried the original LN_GROW_LAYERS and got a segmentation fault.. maybe it is something lurking under the surface. Just weird that midGM is working?!

### output files

rim_layers_equidist.nii
rim_layers_equivol.nii
rim_metric_equidist.nii
rim_metric_equivol.nii
rim_midGM_equidist.nii
rim_midGM_equivol.nii

### here is the terminal output 

```
LN2_LAYERS -rim rim.nii -nr_layers 20 -equivol -iter_smooth 100
=======================
LAYNII v2.2.1dev          
=======================
LN2_LAYERS

    File name: rim.nii
    Image details: 421 X | 430 Y | 255 Z | 0 T 
    Voxel size = 0.25 x 0.25 x 0.25
    Datatype = 4

  Nr. layers: 20
  Rim file voxel sparsity 0%

  Start growing from inner GM (WM-facing border)...

  Start growing from outer GM...

  Start layering (equi-distant)...

  Start mildly smoothing equidistant cortical depths...

  Saving equidistant metric and layers files...
    Writing output as:
      rim_metric_equidist.nii
    Writing output as:
      rim_layers_equidist.nii

  Start finding middle gray matter (equi-distant)...
    Writing output as:
      rim_midGM_equidist.nii

  Start equi-volume stage...

  Start computing equi-volume factors...

  Start smoothing equi-volume transitions...

  Start final layering...
    Writing output as:
      rim_layers_equivol.nii

  Start mildly smoothing equivolume cortical depth...

  Saving equivolume metric and layers files...
    Writing output as:
      rim_metric_equivol.nii
    Writing output as:
      rim_layers_equivol.nii

  Start finding middle gray matter (equi-volume)...
    Writing output as:
      rim_midGM_equivol.nii
```

**Comment by ofgulban** [comment]
Hmm, then maybe send me your rim file and I can quickly check. I recommend using LN2_LAYERS, older program are there backwards compatibility

**Comment by ravenep** [comment]
Ok, thanks, I will send it now. LN2_LAYERS is definitely my preference. I wasn't sure if we could learn something using the old code.

**Comment by ravenep** [comment]
Just realized I can paste a link, here it is, https://drive.google.com/drive/folders/1avaTRcbTmnpaFFuhLwK-dFlQna2uh1RR?usp=sharing

**Comment by ravenep** [comment]
thanks for that insight, I would not have checked that detail. This is a very useful workaround, and solves my problem :)
