### ISSUE TITLE
A question about the usage of LayNii in Huber et al 2018.

### ISSUE THREAD

**Issue by layerConnectome** [layerfMRI/LAYNII#58]
For the EPI image of multiple slices, when drawing the CSF-gray matter boundary and the gray matter-white matter boundary, should I draw this for each slice of a given ROI, or should I just draw it for a single slice?

For example, if I'd like to reproduce the results in this paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5739950/), should I draw the boundary for only one slice or multiple slices?

Thank you.

**Comment by ofgulban** [comment]
Thanks for your question @layerConnectome ,

I am assuming that you are planning to use e.g. `LN2_LAYERS` program to compute the cortical depths. If this is correct, then you need the CSF-gray matter and white matter - gray matter boundaries for each slice for the correct computation of the cortical depth and thickness of each gray matter voxel. This video might give how the inputs and outputs look like to use `LN2_LAYERS` in the intended way: https://youtu.be/kTiVAb4MLQ4 . Further details can be found in: https://thingsonthings.org/ln2_layers/ . You can manually draw these boundaries or use automatic or semi-automatic methods to segment the images

If you are asking if that paper segmented multiple slices, I do not know as I was not involved. Therefore tagging @layerfMRI .

**Comment by layerfMRI** [comment]
Hi @layerConnectome, 

Yes, I can confirm this. The Layer-growing in 2014-2017 was using an older version. It was not called LayNii yet. This program was used: https://github.com/layerfMRI/repository/tree/master/ODIN_related/GROW_LAYERS 

If I remember correctly, the ROI covered 1-3 slices out of a very thin slab. Maybe the following post about ROI selection is helpful:  https://layerfmri.com/2018/03/13/finding-roi-of-the-double-layers-in-m1/

**Comment by ofgulban** [comment]
@layerConnectome is your question answered? If there is no response within I am going to close this issue soon.
