### ISSUE TITLE
Separate test data from repository

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#6]
- @layerfMRI we need to prepare a common set of nifti files that can be used to test every program. So far I am missing proper inputs for:
  - [x] `LN_3DCOLUMNS` requires `layers.nii` (`layers_large.nii` already available in `test_data` folder is too big for testing) 
  - [x] `LN_COLUMNAR` requies `layers.nii`
  - [x] `LN_IMAGIRO` requires `columnar_coordinated.nii` and `data2unfold.nii`

  - [x] `LN_BOCO` required `Nulled_intemp.nii` and `BOLD_intemp.nii` (I have acquired these files from you but just noting it here to not forget).

- ~~Create a separate source for test images (e.g. use zenodo?).~~
- ~~Remove nifti images from `test_data` folder.~~

**Comment by layerfMRI** [comment]
I added a more complete set of example data. for all the LAYNII programs, now.
-still missing are the Nulled_interp.nii and BOLD_interp.nii 
-do you think we should also include datasets in different datatypes 8bit, 16bit, 32bit etc. E.g. for debugging purposes?
-as long as the data size can be kept small enough to fit the restrictions from github, it would make sense to store them all at one place. (at least assuming that the purpose of these data is to test the software).

**Comment by layerfMRI** [comment]
the timeseries data are also uploaded now. At a lower resolution though.

**Comment by ofgulban** [comment]
@layerfMRI thanks for the update. About:
2. I don't think it is needed. The new datatype conversion function in `devel` brainch will handle all those cases in the future.
3. I agree that downsampled data can be kept here. Good idea ! :)

**Comment by ofgulban** [comment]
We have updated the test_data folder and tested each program by using the data available in that folder. Closing issue.
