### ISSUE TITLE
The part about docker is not released (yet)

### ISSUE THREAD

**Issue by layerfMRI** [layerfMRI/LAYNII#60]
I noticed that the changes from March by @Remi-Gau are not yet in the latest releases. 
@ofgulban do you mind creating a new version and a new release? I would add the M1 and the Mac intel binaries retrospectively (as usual).
If you meant to wait with for anything specific before the release, thats fine too. 
Best, Renzo

**Comment by layerfMRI** [comment]
In order for the docker builder to work, we would need to deal with the new things in laynii_lib
That version cannot deal with the 

<<<<<<< HEAD
=======
>>>>>>> devel

part.
do we rely on this? or can we remove it?

**Comment by Remi-Gau** [comment]
Looks like you have unsolved merged Co flicts that were merged in.

I can have a quick look and make a clean up PR when I get home.

**Comment by ofgulban** [comment]
@Remi-Gau and @layerfMRI , v2.3.0 is released now. @layerfMRI feel free to add the Mac compiled binaries to the release.

**Comment by layerfMRI** [comment]
M1 binaries are added now

**Comment by layerfMRI** [comment]
If nobody objects, I would also add the test data into the Docker file (docker image). This will be handy for some of the upcoming LayNii trainings. 
Its in the devel branch for now.

**Comment by Remi-Gau** [comment]
From memory the docker image is small, so adding some data into it should not bloat it too much I think.

**Comment by layerfMRI** [comment]
cool. 
Yes the docker is now 324.9MB (including 80MB for test data).

**Comment by Remi-Gau** [comment]
yeah compare to some of the gigantic 15Go of some bids app I deal with these days, Laynii is cute.

**Comment by Remi-Gau** [comment]
other possibility is to have 2 dockerfiles one with data and one without

**Comment by ofgulban** [comment]
I would prefer fewer files and less complication. Therefore, I strongly favor one file that has the data included. The total size is pretty small anyway.
