### ISSUE TITLE
build and push new docker image to docker hub on release

### ISSUE THREAD

**Issue by Remi-Gau** [layerfMRI/LAYNII#64]
slowly discovering on some other projects that the building of docker images should also be tested regularly

I could set up a circle ci workflow to automatically build and push a docker image of laynii to docker hub upon release.

Good thing for users is that this way they do not have to build the image, they can just download it.

**Comment by layerfMRI** [comment]
But thanks for the offer Remi, thats nice of you. 
I do not have the expertise to have an opinion on the benefit (and burden) of this. And I have no strong preference. I also do not know how much effort it would be from your side.

I don't mind keeping it simple and manual.

So far, I was just adding it to do docker hub 'manually'. 
https://hub.docker.com/repositories/layerfmri 
I am happy to continue doing this in the future too. It does not take longer than five minutes.

**Comment by ofgulban** [comment]
If @layerfMRI is ok with doing it manually, I would prefer to not have circle ci integration. Maybe in the future we can take up on your offer if it becomes cumbersome to upload manually.

**Comment by Remi-Gau** [comment]
no worries

in the mean time this link should probably be added to the readme

https://hub.docker.com/repositories/layerfmri

I was not aware that those images were on dockerhub, hence why I opened the issue.

**Comment by ofgulban** [comment]
@Remi-Gau Thanks for the tip, I have added the link to the readme.

**Comment by ofgulban** [comment]
Closing this issue for now. We can reconsider in the future.
