### ISSUE TITLE
Question about creating EPI reference 

### ISSUE THREAD

**Issue by zqsha** [layerfMRI/LAYNII#81]
Hi experts,
I am not sure whether it's the correct section to ask questions about generating EPI reference, as I previously posted these questions in https://github.com/kenshukoiso/Whole_Brain_Project/, however, there is no reply. So, I try to ask these questions here. I just have a couple of questions about the scripts for generating EPI reference, this might involve `m01_start_bias_field.sh`, `m02_denoise_me.sh` and `m03_regist_ANAT2EPI.sh`.  These scripts already showed very detailed information about how to get EPI reference, however, I just wanted to make sure about the variables without annotations.

**Question 1: In the f02_average_run.sh, Line 19: fslmaths $1 -mul 2000 $1 -odt short**
Because this "$1" is not indicated, so I am not sure what it refers to. However, I noticed that the output file is not used in the follow-up analysis. So, can I ignore this command?

**Question 2: In the m01_start_bias_field.sh, Line 6: cp $1 uncorr.n**ii
Even though "$1" is not specified in the script, I guess "$1" this variable refers to the T1w.nii generated from f03_BOCO.sh. Am I correct?

**Question 3: In the m02_denoise_me.sh, Line 3, DenoiseImage -d 3 -n Rician -i $1 -o denoised_$1**
Despite the "$1" is not specified in the script, but I guess this variable refers to the bico_T1w.nii, which is generated by Bias_field_script_job.m. Is it correct?

Thank you so much. Looking forward to your reply.

Best,
Cain

**Comment by ofgulban** [comment]
Tagging @layerfMRI and @kenshukoiso

**Comment by kenshukoiso** [comment]
Hi Cain,
I am sorry for my late response. I will reply to you later today.
Best regards,
Kenshu

**Comment by ofgulban** [comment]
Is there any movement on this? Have you replied maybe in private @kenshukoiso ?

**Comment by kenshukoiso** [comment]
Yes, I have answered in my issue page. You can close this issue. Sorry for your trouble.
