### ISSUE TITLE
Remove noise on the VASO images

### ISSUE THREAD

**Issue by zqsha** [layerfMRI/LAYNII#82]
Hi experts,
Recently, I created the mean VASO image, which will be used for registration with anatomical image. However, I found the noise outside the brain is a bit annoying (please see below). The noise could affect the follow-up registration with the anatomical image.
I just remember LN_MP2RAGE_DNOISE can remove the noise outside the brain in the MP2RAGE image (https://layerfmri.com/2019/06/22/mp2rage/). This website also showed that a background removal algorithm can also be quite nifty in VASO layer-fMRI. But, I am not sure whether this algorithm has been integrated to LAYNII tool. If so, I do not know how I remove the noise outside the brain by using some functions from LAYNII. Do you have any suggestions? Thank you so much in advance.
![image](https://github.com/layerfMRI/LAYNII/assets/27337033/b9f9aad1-0374-4c8e-8426-e4e286d2c4d3)

Best,
Cain

**Comment by layerfMRI** [comment]
Dear @zqsha,

I can confirm that this program is part of LayNii and I confirm that this program has been developed for the application with layer-fmri VASO data.
The only reason, why it's be contains MP2RAGE is to give credit to the original author's of the algorithm, who did it forMP2RAGE (O'Brian er al.).

Note that, dependent on the inversion times used, and dependent on the EPI background signal (e.g. ghost level), you might want to increase the regularization parameter. E.g. 
`LN_MP2RAGE_DNOISE -INV1 mean_nulled.nii -INV2 mean_not_nulled.nii -UNI mean_VASO.nii -beta 15`


I am not sure if this resolves the question, if not please clarify.

**Comment by zqsha** [comment]
Hi experts,
Thank you so much for your help. I just now tried to use this function to remove the noise on VASO images, it's working very well now. Thanks.
Best,
Cain
