### ISSUE TITLE
v2.5.1 for Linux, is it missing?

### ISSUE THREAD

**Issue by ulloaa** [layerfMRI/LAYNII#83]
Hello,

I was about to download v2.5.1 for Linux but I noticed the name of the file is 

LayNii_v2.5.0_Linux64.zip

Is this just an error in naming the file or is 2.5.1 for Linux not available yet?

Thanks!

**Comment by ofgulban** [comment]
Hello,
Thanks for noticing this, i have compiled and intended to upload v2.5.1 zip but maybe misclicked on the wrong zip. The difference between v2.5.1 and v2.5.0 is just that v2.5.1 says "LayNii v2.5.1" when you execute a program versus v2.5.0 says "LayNii v2.4.0". So the difference is purely cosmetic.

As I am away from office until August, i recommend you to use v2.5.0. I will compile and update the zip once I return.

**Comment by layerfMRI** [comment]
The Linus binaries for v2.5.1 are now uploaded to the release: [https://github.com/layerfMRI/LAYNII/releases/tag/v2.5.1](https://github.com/layerfMRI/LAYNII/releases/tag/v2.5.1 )

**Comment by ofgulban** [comment]
Thanks @layerfMRI !

**Comment by ulloaa** [comment]
Great, thank you!
