### ISSUE TITLE
Tutorials for LN2_COLUMNS

### ISSUE THREAD

**Issue by zqsha** [layerfMRI/LAYNII#84]
Hi experts,
Recently, I wanted to generate column-like ROIs in grey matter. In this LAYNII toolbox, I noticed a function, called LN2_COLUMNS, which could be helpful to accomplish my goals. However, I did not find any annotations for this function. Is there any tutorials on this function that I can refer to? Thank you so much.

PS. I found a tutorial for another similar function, called LN_COLUMNAR_DIST. But, I guess it might be not related to my research aims.

Best,
Cain

**Comment by ofgulban** [comment]
Dear Cain,
Thanks for your question. If read the help menu of LN2_COLUMNS carefully, you can see that there is a note on the further details:

    "Notes:\n"
    "    - You can find further explanation of this algorithm at:\n"
    "      <https://thingsonthings.org/ln2_columns>\n"
    
Please note that we take take mentioning further reading in our programs' help menus when we have supporting text and other materials available.

Hope the blog post will be useful. Please do not hesitate to ask further questions.

**Comment by zqsha** [comment]
Hi expert,
Thanks for your reply. That's very helpful. This tutorial has helped me to accomplish my analysis.

Best,
Cain

**Comment by ofgulban** [comment]
Great, thanks for letting us know Cain, and please don't hesitate to ask questions in the future.
