### ISSUE TITLE
Add custom path support for output names

### ISSUE THREAD

**Issue by ofgulban** [layerfMRI/LAYNII#9]
As seen in #2 custom output paths would be useful as a general optional CLI flag for all `LAYNII` programs and accommodate people with different file naming preferences (e.g. using suffix instead of prefix).

**Comment by ofgulban** [comment]
- v1.5.0: Outputs are switched to use suffix tags instead of prefix. 
- v1.5.0: LAYNII now can handle absolute and relative input path names and saved the output in the input folder.

Custom output flag will be added to each program in a later version (>1.5.0).

**Comment by ofgulban** [comment]
- v1.5.1: Introducing custom output path in `LN_BOCO`, `LN_MP2RAGE_DNOISE`, `LN_FLOAT_ME`, `LN_SHORT_ME`, `LN_INT_ME`. This flag will also be added to other programs as needed in the future.

**Comment by layerfMRI** [comment]
v1.5.6 now has custom output names for all remaining programs via an optional -output flag. 
This custom output can contain the relative or absolute path to the file. (important if LAYNI is dockerized). 
When not file path is given, the file is written in the local folder of exceution. 
This output file name can also contain the file type. e.g. znii or .nii.gz
